# Generated by Django 4.2.30 on 2026-04-12 02:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código do Curso (000/AAAA)')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='EncontroPresencial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('turno', models.CharField(choices=[('MANHA', 'Manha'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10)),
                ('local', models.CharField(max_length=255, verbose_name='Local (Sala/Auditório)')),
            ],
            options={
                'db_table': 'encontros_presenciais',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CURSANDO', 'Cursando'), ('CONCLUIDA', 'Concluída'), ('DESISTENTE', 'Desistente (Suspensão)')], default='PENDENTE', max_length=20)),
                ('dados_extras', models.JSONField(blank=True, help_text='Usado se o curso exige preenchimento de requisitos específicos no momento da inscrição.', null=True, verbose_name='Dados Extras da Matrícula')),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matriculas',
            },
        ),
        migrations.CreateModel(
            name='ModuloDigital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('url_youtube', models.URLField(verbose_name='Link do YouTube')),
                ('carga_horaria_minutos', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'modulos_digitais',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, verbose_name='Código da Turma (Ex: T01)')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('PREVISTA', 'Prevista'), ('CONCLUIDA', 'Concluída'), ('FINALIZADA', 'Finalizada'), ('ADIADA', 'Adiada'), ('CANCELADA', 'Cancelada')], default='PREVISTA', max_length=20, verbose_name='Status da Turma')),
                ('vagas', models.PositiveIntegerField(default=30)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='academics.curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turmas',
            },
        ),
    ]
