# Generated by Django 4.2.30 on 2026-04-12 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_lecionadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulodigital',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_digitais', to='academics.turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academics.turma'),
        ),
        migrations.AddField(
            model_name='encontropresencial',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encontros_presenciais', to='academics.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('curso', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudante', 'turma')},
        ),
    ]
