# Generated by Django 4.2.30 on 2026-04-13 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('eixo', models.CharField(choices=[('TECNOLOGIA', 'Tecnologia'), ('TECNICO_ESPECIALIZADO', 'Técnico Especializado'), ('RELACOES_HUMANAS', 'Relações Humanas'), ('GESTAO_PUBLICA', 'Gestão Pública'), ('CONTABILIDADE_FINANCAS', 'Contabilidade, Finanças e Previdência')], default='GESTAO_PUBLICA', max_length=50, verbose_name='Eixo Tecnológico')),
                ('num_processo', models.CharField(max_length=50, verbose_name='Nº do Processo')),
                ('memorando', models.CharField(max_length=50, verbose_name='Memorando de Solicitação')),
                ('tipo', models.CharField(choices=[('CENTRALIZADO', 'Centralizado'), ('DESCENTRALIZADO', 'Descentralizado')], default='CENTRALIZADO', max_length=20, verbose_name='Tipo')),
                ('codigo_oficial', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código Oficial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'catalogo_cursos',
                'ordering': ['-codigo_oficial'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=3, verbose_name='Letra da Turma')),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto (EAD)'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=20, verbose_name='Modalidade')),
                ('vagas', models.PositiveIntegerField(default=30, verbose_name='Nº de Vagas')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo (R$)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('status_manual', models.CharField(blank=True, choices=[('PREVISTA', 'Prevista'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('FINALIZADA', 'Finalizada'), ('ADIADA', 'Adiada'), ('CANCELADA', 'Cancelada')], help_text='Preencha apenas para Finalizado, Adiado ou Cancelado.', max_length=20, null=True, verbose_name='Status Manual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cursos.curso', verbose_name='Curso')),
                ('instrutor', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'INSTRUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_instruidas', to=settings.AUTH_USER_MODEL, verbose_name='Instrutor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'catalogo_turmas',
                'ordering': ['curso', 'letra'],
                'unique_together': {('curso', 'letra')},
            },
        ),
        migrations.CreateModel(
            name='EventoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('espaco', models.CharField(choices=[('LAB_INFO', 'Laboratório de Informática - 4º andar (30 vagas)'), ('SALA_1', 'Sala de Aula 1 - 4º andar (21 vagas)'), ('SALA_2', 'Sala de Aula 2 - 5º andar (33 vagas)'), ('AUDITORIO', 'Auditório - 5º andar (60 vagas)'), ('EXTERNO', 'Espaço Externo / Outros')], max_length=20)),
                ('espaco_externo_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Local Externo')),
                ('turno_reserva', models.CharField(choices=[('MANHA', 'Manhã (08h às 12h)'), ('TARDE', 'Tarde (13h às 17h)'), ('NOITE', 'Noite (18h às 22h)')], editable=False, max_length=10)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cursos.turma')),
            ],
            options={
                'verbose_name': 'Evento da Turma',
                'verbose_name_plural': 'Eventos da Turma',
                'db_table': 'catalogo_eventos_turma',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado_chefia', 'Aprovado pela Chefia'), ('inscrito', 'Inscrito'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('hash_validacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='cursos.turma')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'catalogo_inscricoes',
                'ordering': ['-data_inscricao'],
                'unique_together': {('perfil', 'turma')},
            },
        ),
    ]
