# Generated by Django 4.2.30 on 2026-04-12 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('num_processo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº do Processo')),
                ('memorando', models.CharField(blank=True, max_length=50, null=True, verbose_name='Memorando')),
                ('tipo', models.CharField(choices=[('CENTRALIZADO', 'Centralizado'), ('DESCENTRALIZADO', 'Descentralizado')], default='CENTRALIZADO', max_length=20, verbose_name='Tipo')),
                ('codigo_oficial', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código Oficial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'catalogo_cursos',
                'ordering': ['-codigo_oficial'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=3, verbose_name='Letra da Turma')),
                ('local', models.CharField(max_length=255, verbose_name='Local / Sala')),
                ('vagas', models.PositiveIntegerField(default=30, verbose_name='Nº de Vagas')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo (R$)')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária (h)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='MANHA', max_length=5, verbose_name='Turno')),
                ('status_manual', models.CharField(blank=True, choices=[('PREVISTA', 'Prevista'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('FINALIZADA', 'Finalizada'), ('ADIADA', 'Adiada'), ('CANCELADA', 'Cancelada')], help_text='Preencha apenas para Finalizado, Adiado ou Cancelado.', max_length=20, null=True, verbose_name='Status Manual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cursos.curso', verbose_name='Curso')),
                ('instrutor', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'INSTRUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_instruidas', to=settings.AUTH_USER_MODEL, verbose_name='Instrutor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'catalogo_turmas',
                'ordering': ['curso', 'letra'],
                'unique_together': {('curso', 'letra')},
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado_chefia', 'Aprovado pela Chefia'), ('inscrito', 'Inscrito'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('hash_validacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Hash de Validação')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL, verbose_name='Perfil do Usuário')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='cursos.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'catalogo_inscricoes',
                'ordering': ['-data_inscricao'],
                'unique_together': {('perfil', 'turma')},
            },
        ),
    ]
