# Generated by Django 4.2.30 on 2026-05-05 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Atividade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Instruções / Texto')),
                ('tipo', models.CharField(choices=[('VIDEO_YOUTUBE', 'Vídeo (YouTube)'), ('LEITURA', 'Material de Leitura / Link'), ('TAREFA', 'Tarefa Prática')], default='VIDEO_YOUTUBE', max_length=20)),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='Link do YouTube')),
                ('carga_horaria_recompensa', models.PositiveIntegerField(default=0, help_text='Quantas horas o aluno ganha ao concluir esta atividade?', verbose_name='Carga Horária (Recompensa)')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('aprovado_admin', models.BooleanField(default=False, help_text='Atividades EAD/Híbrido só somam carga horária após aprovação do administrador.', verbose_name='Aprovado pelo Admin')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'lms_atividades',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('eixo', models.CharField(choices=[('TECNOLOGIA', 'Tecnologia'), ('TECNICO_ESPECIALIZADO', 'Técnico Especializado'), ('RELACOES_HUMANAS', 'Relações Humanas'), ('GESTAO_PUBLICA', 'Gestão Pública'), ('CONTABILIDADE_FINANCAS', 'Contabilidade, Finanças e Previdência')], default='GESTAO_PUBLICA', max_length=50, verbose_name='Eixo Tecnológico')),
                ('num_processo', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº do Processo')),
                ('memorando', models.CharField(blank=True, default='', max_length=50, verbose_name='Memorando de Solicitação')),
                ('tipo', models.CharField(choices=[('CENTRALIZADO', 'Centralizado'), ('DESCENTRALIZADO', 'Descentralizado')], default='CENTRALIZADO', max_length=20, verbose_name='Tipo')),
                ('codigo_oficial', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código Oficial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'catalogo_cursos',
                'ordering': ['-codigo_oficial'],
            },
        ),
        migrations.CreateModel(
            name='EspacoAlocado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espaco', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('turno_reserva', models.CharField(max_length=10)),
                ('evento_ref', models.CharField(blank=True, help_text="Referência interna: 'evento_<id>' ou 'item_<id>'", max_length=50, null=True)),
            ],
            options={
                'db_table': 'catalogo_espaco_alocado',
            },
        ),
        migrations.CreateModel(
            name='EventoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('espaco', models.CharField(choices=[('LAB_INFO', 'Laboratório de Informática - 4º andar (30 vagas)'), ('SALA_1', 'Sala de Aula 1 - 4º andar (21 vagas)'), ('SALA_2', 'Sala de Aula 2 - 5º andar (33 vagas)'), ('AUDITORIO', 'Auditório - 5º andar (60 vagas)'), ('EXTERNO', 'Espaço Externo / Outros')], max_length=20)),
                ('espaco_externo_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Local Externo')),
                ('turno_reserva', models.CharField(choices=[('MANHA', 'Manhã (08h às 12h)'), ('TARDE', 'Tarde (13h às 17h)'), ('NOITE', 'Noite (18h às 22h)')], editable=False, max_length=10)),
            ],
            options={
                'verbose_name': 'Evento da Turma',
                'verbose_name_plural': 'Eventos da Turma',
                'db_table': 'catalogo_eventos_turma',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('NOTA_ALTERADA', 'Nota Alterada'), ('PRESENCA_ALTERADA', 'Presença Alterada'), ('DIARIO_FECHADO', 'Diário Fechado')], max_length=30, verbose_name='Tipo de Ação')),
                ('tabela_referencia', models.CharField(max_length=80, verbose_name='Tabela/Objeto')),
                ('objeto_id', models.CharField(max_length=50, verbose_name='ID do Objeto')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
            ],
            options={
                'verbose_name': 'Histórico de Alteração',
                'verbose_name_plural': 'Histórico de Alterações',
                'db_table': 'catalogo_auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado_chefia', 'Aprovado pela Chefia'), ('inscrito', 'Inscrito'), ('concluido', 'Concluído'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Final')),
                ('hash_validacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('ip_aprovacao', models.GenericIPAddressField(blank=True, null=True)),
                ('justificativa_rejeicao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'catalogo_inscricoes',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='ItemReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('espaco', models.CharField(choices=[('LAB_INFO', 'Laboratório de Informática - 4º andar (30 vagas)'), ('SALA_1', 'Sala de Aula 1 - 4º andar (21 vagas)'), ('SALA_2', 'Sala de Aula 2 - 5º andar (33 vagas)'), ('AUDITORIO', 'Auditório - 5º andar (60 vagas)'), ('EXTERNO', 'Espaço Externo / Outros')], max_length=20)),
                ('data', models.DateField()),
                ('turno_reserva', models.CharField(choices=[('MANHA', 'Manhã (08h às 12h)'), ('TARDE', 'Tarde (13h às 17h)'), ('NOITE', 'Noite (18h às 22h)')], editable=False, max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
            options={
                'verbose_name': 'Item de Reserva',
                'verbose_name_plural': 'Itens de Reserva',
                'db_table': 'catalogo_itens_reserva',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Módulo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'lms_modulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=True)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lms_progresso_alunos',
            },
        ),
        migrations.CreateModel(
            name='ProgressoSessaoEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_ping', models.DateTimeField(auto_now_add=True)),
                ('duracao_minutos', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'lms_progresso_sessoes_ead',
                'ordering': ['-timestamp_ping'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('JUSTIFICADA', 'Falta Justificada')], default='PRESENTE', max_length=20, verbose_name='Status de Presença')),
            ],
            options={
                'verbose_name': 'Registro de Presença',
                'verbose_name_plural': 'Registros de Presença',
                'db_table': 'catalogo_presencas',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Evento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Evento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status da Solicitação')),
                ('protocolo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Protocolo')),
                ('justificativa_recusa', models.TextField(blank=True, null=True, verbose_name='Justificativa (em caso de recusa)')),
                ('avaliado_em', models.DateTimeField(blank=True, null=True)),
                ('ip_avaliacao', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Reserva',
                'verbose_name_plural': 'Solicitações de Reserva',
                'db_table': 'catalogo_solicitacoes_reserva',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=3, verbose_name='Letra da Turma')),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto (EAD)'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=20, verbose_name='Modalidade')),
                ('visibilidade', models.CharField(choices=[('PUBLICA', 'Pública (Catálogo Aberto)'), ('RESTRITA', 'Restrita (Inscrição Manual)')], default='PUBLICA', max_length=20, verbose_name='Visibilidade da Turma')),
                ('vagas', models.PositiveIntegerField(default=30, verbose_name='Nº de Vagas')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo (R$)')),
                ('carga_horaria', models.PositiveIntegerField(default=0, verbose_name='Carga Horária (h)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('status_manual', models.CharField(blank=True, choices=[('PREVISTA', 'Prevista'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('FINALIZADA', 'Finalizada'), ('ADIADA', 'Adiada'), ('CANCELADA', 'Cancelada')], help_text='Preencha apenas para Finalizado, Adiado ou Cancelado.', max_length=20, null=True, verbose_name='Status Manual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('diario_fechado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'catalogo_turmas',
                'ordering': ['curso', 'letra'],
            },
        ),
        migrations.CreateModel(
            name='TurmaGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Gestor da Turma',
                'verbose_name_plural': 'Gestores das Turmas',
                'db_table': 'catalogo_turma_gestores',
            },
        ),
    ]
