# Generated by Django 4.2.30 on 2026-05-05 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmagestor',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_gerenciadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turmagestor',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestores_associados', to='cursos.turma'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cursos.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='diario_fechado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_fechados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turma',
            name='instrutor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'INSTRUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_instruidas', to=settings.AUTH_USER_MODEL, verbose_name='Instrutor'),
        ),
        migrations.AddField(
            model_name='solicitacaoreserva',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_reserva', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoreserva',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_reserva', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registropresenca',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_evento', to='cursos.eventoturma'),
        ),
        migrations.AddField(
            model_name='registropresenca',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='cursos.inscricao'),
        ),
        migrations.AddField(
            model_name='progressosessaoead',
            name='progresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='cursos.progressoatividade'),
        ),
        migrations.AddField(
            model_name='progressoatividade',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='cursos.atividade'),
        ),
        migrations.AddField(
            model_name='progressoatividade',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='cursos.inscricao'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.turma'),
        ),
        migrations.AddField(
            model_name='itemreserva',
            name='alocacao_fisica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.espacoalocado'),
        ),
        migrations.AddField(
            model_name='itemreserva',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cursos.solicitacaoreserva'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='cursos.turma'),
        ),
        migrations.AddField(
            model_name='historicoalteracao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_alteracoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AddField(
            model_name='eventoturma',
            name='alocacao_fisica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.espacoalocado'),
        ),
        migrations.AddField(
            model_name='eventoturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cursos.turma'),
        ),
        migrations.AddConstraint(
            model_name='espacoalocado',
            constraint=models.UniqueConstraint(condition=models.Q(('espaco', 'EXTERNO'), _negated=True), fields=('data', 'turno_reserva', 'espaco'), name='unique_reserva_turno_espaco'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='cursos.modulo'),
        ),
        migrations.AddConstraint(
            model_name='turmagestor',
            constraint=models.UniqueConstraint(fields=('turma', 'gestor'), name='unique_turma_gestor'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.CheckConstraint(check=models.Q(('custo__gte', 0)), name='chk_custo_positivo'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('curso', 'letra')},
        ),
        migrations.AddConstraint(
            model_name='registropresenca',
            constraint=models.UniqueConstraint(fields=('inscricao', 'evento'), name='unique_inscricao_evento'),
        ),
        migrations.AddConstraint(
            model_name='progressoatividade',
            constraint=models.UniqueConstraint(fields=('inscricao', 'atividade'), name='unique_inscricao_atividade'),
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(fields=('perfil', 'turma'), name='unique_perfil_turma'),
        ),
    ]
