# Generated by Django 4.2.30 on 2026-04-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=0, verbose_name='Carga Horária (h)'),
        ),
    ]
