# Generated by Django 4.2.30 on 2026-05-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='apenas_cadastro_manual',
            field=models.BooleanField(default=False, help_text='Se ativo, o aluno não consegue se inscrever sozinho.', verbose_name='Apenas Matrícula Manual'),
        ),
        migrations.AddField(
            model_name='turma',
            name='vinculos_permitidos',
            field=models.JSONField(blank=True, default=list, help_text="Lista de tipos de usuário. Ex: ['SERVIDOR_ATIVO', 'ESTAGIARIO']. Vazio = todos.", verbose_name='Vínculos Permitidos'),
        ),
        migrations.AlterField(
            model_name='eventoturma',
            name='espaco',
            field=models.CharField(choices=[('LAB_INFO', 'Laboratório de Informática - 4º andar (30 vagas)'), ('SALA_1', 'Sala de Aula 1 - 4º andar (21 vagas)'), ('SALA_2', 'Sala de Aula 2 - 5º andar (33 vagas)'), ('AUDITORIO', 'Auditório - 5º andar (60 vagas)'), ('EXTERNO', 'Espaço Externo / Outros'), ('ONLINE', 'Ambiente Virtual / EAD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemreserva',
            name='espaco',
            field=models.CharField(choices=[('LAB_INFO', 'Laboratório de Informática - 4º andar (30 vagas)'), ('SALA_1', 'Sala de Aula 1 - 4º andar (21 vagas)'), ('SALA_2', 'Sala de Aula 2 - 5º andar (33 vagas)'), ('AUDITORIO', 'Auditório - 5º andar (60 vagas)'), ('EXTERNO', 'Espaço Externo / Outros'), ('ONLINE', 'Ambiente Virtual / EAD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='turma',
            name='letra',
            field=models.CharField(blank=True, max_length=5, verbose_name='Letra da Turma'),
        ),
    ]
