# Generated by Django 4.2.30 on 2026-04-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_inscricao_aprovado_em_inscricao_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='ip_aprovacao',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
