# Generated by Django 4.2.30 on 2026-05-06 05:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_turma_apenas_cadastro_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('VIDEO_YOUTUBE', 'Vídeo (YouTube)'), ('LEITURA', 'Material de Leitura / Link'), ('TAREFA', 'Tarefa Prática'), ('QUESTIONARIO', 'Questionário Avaliativo')], default='VIDEO_YOUTUBE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado_chefia', 'Aprovado pela Chefia'), ('inscrito', 'Inscrito'), ('fila_espera', 'Fila de Espera'), ('concluido', 'Concluído'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tentativas_permitidas', models.IntegerField(default=1)),
                ('nota_minima_aprovacao', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('atividade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionario', to='cursos.atividade')),
            ],
            options={
                'db_table': 'lms_questionarios',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='cursos.questionario')),
            ],
            options={
                'db_table': 'lms_questoes',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('is_correta', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='cursos.questao')),
            ],
            options={
                'db_table': 'lms_opcoes',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('opcao_selecionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.opcao')),
                ('progresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='cursos.progressoatividade')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.questao')),
            ],
            options={
                'db_table': 'lms_respostas_alunos',
                'unique_together': {('progresso', 'questao')},
            },
        ),
    ]
