# Generated by Django 4.2.30 on 2026-05-06 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_atividade_tipo_alter_inscricao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressoatividade',
            name='nota_obtida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Normalizada (0 a 10)'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='tempo_limite_minutos',
            field=models.IntegerField(default=0, help_text='0 significa sem tempo limite'),
        ),
        migrations.CreateModel(
            name='TentativaQuestionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_tentativa', models.IntegerField(default=1)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('nota_obtida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('progresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='cursos.progressoatividade')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.questionario')),
            ],
            options={
                'db_table': 'lms_tentativas_questionario',
            },
        ),
        migrations.AlterUniqueTogether(
            name='respostaaluno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='respostaaluno',
            name='tentativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='cursos.tentativaquestionario'),
        ),
        migrations.AlterUniqueTogether(
            name='respostaaluno',
            unique_together={('tentativa', 'questao')},
        ),
        migrations.RemoveField(
            model_name='respostaaluno',
            name='progresso',
        ),
    ]
