# Generated by Django 4.2.30 on 2026-04-17 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0004_inscricao_ip_aprovacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Evento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Evento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status da Solicitação')),
                ('protocolo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Protocolo')),
                ('justificativa_recusa', models.TextField(blank=True, null=True, verbose_name='Justificativa (em caso de recusa)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_reserva', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Reserva',
                'verbose_name_plural': 'Solicitações de Reserva',
                'db_table': 'catalogo_solicitacoes_reserva',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('espaco', models.CharField(choices=[('LAB_INFO', 'Laboratório de Informática - 4º andar (30 vagas)'), ('SALA_1', 'Sala de Aula 1 - 4º andar (21 vagas)'), ('SALA_2', 'Sala de Aula 2 - 5º andar (33 vagas)'), ('AUDITORIO', 'Auditório - 5º andar (60 vagas)'), ('EXTERNO', 'Espaço Externo / Outros')], max_length=20)),
                ('data', models.DateField()),
                ('turno_reserva', models.CharField(choices=[('MANHA', 'Manhã (08h às 12h)'), ('TARDE', 'Tarde (13h às 17h)'), ('NOITE', 'Noite (18h às 22h)')], editable=False, max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cursos.solicitacaoreserva')),
            ],
            options={
                'verbose_name': 'Item de Reserva',
                'verbose_name_plural': 'Itens de Reserva',
                'db_table': 'catalogo_itens_reserva',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
