# Generated by Django 4.2.30 on 2026-04-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_solicitacaoreserva_itemreserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Final'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado_chefia', 'Aprovado pela Chefia'), ('inscrito', 'Inscrito'), ('concluido', 'Concluído'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True, verbose_name='Presente?')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_evento', to='cursos.eventoturma')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='cursos.inscricao')),
            ],
            options={
                'verbose_name': 'Registro de Presença',
                'verbose_name_plural': 'Registros de Presença',
                'db_table': 'catalogo_presencas',
                'unique_together': {('inscricao', 'evento')},
            },
        ),
    ]
