# Generated by Django 4.2.30 on 2026-05-06 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0005_progressoatividade_nota_obtida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='carga_horaria_recompensa',
        ),
        migrations.AddField(
            model_name='atividade',
            name='atividade_pre_requisito',
            field=models.ForeignKey(blank=True, help_text='O aluno só verá esta atividade após concluir a atividade selecionada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_dependentes', to='cursos.atividade', verbose_name='Atividade Pré-requisito'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_liberacao',
            field=models.DateTimeField(blank=True, help_text='Se preenchido, a atividade só será visível para o aluno após esta data e hora.', null=True, verbose_name='Data/Hora de Liberação'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='atividade_pre_requisito',
            field=models.ForeignKey(blank=True, help_text='Este módulo só será exibido ao aluno após conclusão da atividade selecionada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desbloqueia_modulos', to='cursos.atividade', verbose_name='Atividade Pré-requisito'),
        ),
        migrations.AddField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('MULTIPLA_ESCOLHA', 'Múltipla Escolha (1 correta)'), ('CAIXAS_SELECAO', 'Caixas de Seleção (várias corretas)'), ('DISSERTATIVA', 'Dissertativa (correção manual)')], default='MULTIPLA_ESCOLHA', max_length=20, verbose_name='Tipo de Questão'),
        ),
        migrations.AddField(
            model_name='respostaaluno',
            name='corrigida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_corrigidas', to=settings.AUTH_USER_MODEL, verbose_name='Corrigida por'),
        ),
        migrations.AddField(
            model_name='respostaaluno',
            name='nota_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Manual (Instrutor)'),
        ),
        migrations.AddField(
            model_name='respostaaluno',
            name='resposta_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta Dissertativa'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='aprovado_admin',
            field=models.BooleanField(default=False, help_text='Atividade só aparece para alunos após aprovação do administrador/instrutor.', verbose_name='Visível para Alunos'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='opcao_selecionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.opcao'),
        ),
    ]
