# Generated by Django 4.2.30 on 2026-04-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_inscricao_nota_alter_inscricao_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropresenca',
            name='presente',
        ),
        migrations.AddField(
            model_name='registropresenca',
            name='status',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('JUSTIFICADA', 'Falta Justificada')], default='PRESENTE', max_length=20, verbose_name='Status de Presença'),
        ),
    ]
