# Generated by Django 4.2.30 on 2026-04-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_remove_registropresenca_presente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='gestores_permitidos',
            field=models.JSONField(blank=True, default=list, verbose_name='CPFs dos Gestores Autorizados'),
        ),
        migrations.AddField(
            model_name='turma',
            name='visibilidade',
            field=models.CharField(choices=[('PUBLICA', 'Pública (Catálogo Aberto)'), ('RESTRITA', 'Restrita (Inscrição Manual)')], default='PUBLICA', max_length=20, verbose_name='Visibilidade da Turma'),
        ),
    ]
