# Generated by Django 4.2.30 on 2026-04-21 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_turma_gestores_permitidos_turma_visibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Módulo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.turma')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'lms_modulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Atividade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Instruções / Texto')),
                ('tipo', models.CharField(choices=[('VIDEO_YOUTUBE', 'Vídeo (YouTube)'), ('LEITURA', 'Material de Leitura / Link'), ('TAREFA', 'Tarefa Prática')], default='VIDEO_YOUTUBE', max_length=20)),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='Link do YouTube')),
                ('carga_horaria_recompensa', models.PositiveIntegerField(default=0, help_text='Quantas horas o aluno ganha ao concluir esta atividade?', verbose_name='Carga Horária (Recompensa)')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='cursos.modulo')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'lms_atividades',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=True)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='cursos.atividade')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='cursos.inscricao')),
            ],
            options={
                'db_table': 'lms_progresso_alunos',
                'unique_together': {('inscricao', 'atividade')},
            },
        ),
    ]
