# Generated by Django 4.2.30 on 2026-04-21 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0009_modulo_atividade_progressoatividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoreserva',
            name='avaliado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoreserva',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_reserva', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoreserva',
            name='ip_avaliacao',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='eventoturma',
            constraint=models.UniqueConstraint(condition=models.Q(('espaco', 'EXTERNO'), _negated=True), fields=('data', 'turno_reserva', 'espaco'), name='unique_reserva_turno_espaco'),
        ),
        migrations.AddConstraint(
            model_name='itemreserva',
            constraint=models.UniqueConstraint(condition=models.Q(('espaco', 'EXTERNO'), _negated=True), fields=('data', 'turno_reserva', 'espaco'), name='unique_item_reserva_turno_espaco'),
        ),
    ]
