# Generated by Django 4.2.30 on 2026-04-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0010_solicitacaoreserva_avaliado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmaGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Gestor da Turma',
                'verbose_name_plural': 'Gestores das Turmas',
                'db_table': 'catalogo_turma_gestores',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='progressoatividade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='registropresenca',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(fields=('perfil', 'turma'), name='unique_perfil_turma'),
        ),
        migrations.AddConstraint(
            model_name='progressoatividade',
            constraint=models.UniqueConstraint(fields=('inscricao', 'atividade'), name='unique_inscricao_atividade'),
        ),
        migrations.AddConstraint(
            model_name='registropresenca',
            constraint=models.UniqueConstraint(fields=('inscricao', 'evento'), name='unique_inscricao_evento'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.CheckConstraint(check=models.Q(('custo__gte', 0)), name='chk_custo_positivo'),
        ),
        migrations.AddField(
            model_name='turmagestor',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_gerenciadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turmagestor',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestores_associados', to='cursos.turma'),
        ),
        migrations.AddConstraint(
            model_name='turmagestor',
            constraint=models.UniqueConstraint(fields=('turma', 'gestor'), name='unique_turma_gestor'),
        ),
    ]
