# Generated by Django 4.2.30 on 2026-04-22 01:49

from django.db import migrations


def copy_gestores(apps, schema_editor):
    Turma = apps.get_model('cursos', 'Turma')
    TurmaGestor = apps.get_model('cursos', 'TurmaGestor')
    Profile = apps.get_model('users', 'Profile')

    for turma in Turma.objects.all():
        if not turma.gestores_permitidos:
            continue
        cpfs = turma.gestores_permitidos
        # cpfs é um list de strings
        profiles = Profile.objects.filter(cpf__in=cpfs)
        for profile in profiles:
            TurmaGestor.objects.get_or_create(turma=turma, gestor=profile)

class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_turmagestor_alter_inscricao_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_gestores, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS public.itens_reserva CASCADE; DROP TABLE IF EXISTS public.solicitacoes_reserva CASCADE;",
            reverse_sql=migrations.RunSQL.noop
        )
    ]
