# Generated by Django 4.2.30 on 2026-04-22 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_auto_20260421_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='gestores_permitidos',
        ),
    ]
