# Generated by Django 4.2.30 on 2026-04-22 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0013_remove_turma_gestores_permitidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacoAlocado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espaco', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('turno_reserva', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'catalogo_espaco_alocado',
            },
        ),
        migrations.CreateModel(
            name='ProgressoSessaoEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_ping', models.DateTimeField(auto_now_add=True)),
                ('duracao_minutos', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'lms_progresso_sessoes_ead',
                'ordering': ['-timestamp_ping'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='eventoturma',
            name='unique_reserva_turno_espaco',
        ),
        migrations.RemoveConstraint(
            model_name='itemreserva',
            name='unique_item_reserva_turno_espaco',
        ),
        migrations.AddField(
            model_name='turma',
            name='diario_fechado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='diario_fechado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_fechados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressosessaoead',
            name='progresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='cursos.progressoatividade'),
        ),
        migrations.AddField(
            model_name='eventoturma',
            name='alocacao_fisica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.espacoalocado'),
        ),
        migrations.AddField(
            model_name='itemreserva',
            name='alocacao_fisica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.espacoalocado'),
        ),
    ]
