# Generated by Django 4.2.30 on 2026-04-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_espacoalocado_progressosessaoead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
