# Generated by Django 4.2.30 on 2026-04-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_atividade_is_active_modulo_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='espacoalocado',
            constraint=models.UniqueConstraint(condition=models.Q(('espaco', 'EXTERNO'), _negated=True), fields=('data', 'turno_reserva', 'espaco'), name='unique_reserva_turno_espaco'),
        ),
    ]
