# Generated by Django 4.2.30 on 2026-04-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_espacoalocado_unique_reserva_turno_espaco'),
    ]

    operations = [
        migrations.RunSQL("""
            -- Eliminação Segura das Tabelas Fantasmas (Dívida Técnica Perpétua)
            DROP TABLE IF EXISTS itens_reserva CASCADE;
            DROP TABLE IF EXISTS solicitacoes_reserva CASCADE;
            
            -- Garantia Absoluta via DDL da Injeção Físico (Bypass no ORM)
            ALTER TABLE catalogo_inscricoes DROP CONSTRAINT IF EXISTS unique_perfil_turma;
            ALTER TABLE catalogo_inscricoes ADD CONSTRAINT unique_perfil_turma UNIQUE (perfil_id, turma_id);
            
            ALTER TABLE catalogo_presencas DROP CONSTRAINT IF EXISTS unique_inscricao_evento;
            ALTER TABLE catalogo_presencas ADD CONSTRAINT unique_inscricao_evento UNIQUE (inscricao_id, evento_id);
        """)
    ]
