# Generated by Django 4.2.30 on 2026-04-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_ddl_zombie_fallback'),
    ]

    operations = [
        migrations.RunSQL("""
            -- Corrige Double Booking definitivamente
            DROP INDEX IF EXISTS unique_espaco_alocado_idx;
            CREATE UNIQUE INDEX unique_espaco_alocado_idx 
            ON public.catalogo_espaco_alocado (data, turno_reserva, espaco) 
            WHERE espaco != 'EXTERNO';

            -- Garante a Inscrição Única
            ALTER TABLE catalogo_inscricoes DROP CONSTRAINT IF EXISTS unique_perfil_turma;
            ALTER TABLE catalogo_inscricoes ADD CONSTRAINT unique_perfil_turma UNIQUE (perfil_id, turma_id);

            -- Garante o Progresso Único EAD
            ALTER TABLE lms_progresso_alunos DROP CONSTRAINT IF EXISTS lms_progresso_ativid_inscricao_id_atividade__ac9bfac6_uniq;
            ALTER TABLE lms_progresso_alunos ADD CONSTRAINT unique_progresso_atividade UNIQUE (inscricao_id, atividade_id);

            -- Garante Frequência Única Presencial
            ALTER TABLE catalogo_presencas DROP CONSTRAINT IF EXISTS unique_inscricao_evento;
            ALTER TABLE catalogo_presencas ADD CONSTRAINT unique_inscricao_evento UNIQUE (inscricao_id, evento_id);
        """)
    ]
