# Generated by Django 4.2.30 on 2026-04-23 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0018_inject_phantom_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='aprovado_admin',
            field=models.BooleanField(default=False, help_text='Atividades EAD/Híbrido só somam carga horária após aprovação do administrador.', verbose_name='Aprovado pelo Admin'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='espacoalocado',
            name='evento_ref',
            field=models.CharField(blank=True, help_text="Referência interna: 'evento_<id>' ou 'item_<id>'", max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('NOTA_ALTERADA', 'Nota Alterada'), ('PRESENCA_ALTERADA', 'Presença Alterada'), ('DIARIO_FECHADO', 'Diário Fechado')], max_length=30, verbose_name='Tipo de Ação')),
                ('tabela_referencia', models.CharField(max_length=80, verbose_name='Tabela/Objeto')),
                ('objeto_id', models.CharField(max_length=50, verbose_name='ID do Objeto')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor Novo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_alteracoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Alteração',
                'verbose_name_plural': 'Histórico de Alterações',
                'db_table': 'catalogo_auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        # ── BLINDAGEM DE BANCO DE DADOS ────────────────────────────────
        # Garante o UNIQUE INDEX diretamente no PostgreSQL, independente
        # de migrations anteriores. "IF NOT EXISTS" é idempotente.
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX IF NOT EXISTS uk_espaco_ocupado
                ON public.catalogo_espaco_alocado (data, turno_reserva, espaco)
                WHERE espaco != 'EXTERNO';
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS public.uk_espaco_ocupado;
            """,
        ),
    ]
