# Generated by Django 4.2.30 on 2026-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_atividade_aprovacao_auditoria_espaco_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='memorando',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Memorando de Solicitação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='num_processo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nº do Processo'),
        ),
    ]
