# Generated by Django 4.2.30 on 2026-04-12 02:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('nome_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Social')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone')),
                ('tipo_usuario', models.CharField(choices=[('SERVIDOR_ATIVO', 'Servidor Ativo'), ('CIDADAO', 'Cidadão'), ('TERCEIRIZADO', 'Terceirizado'), ('ESTAGIARIO', 'Estagiário'), ('INSTRUTOR', 'Instrutor')], default='CIDADAO', max_length=20, verbose_name='Tipo de Usuário')),
                ('dados_servidor', models.JSONField(blank=True, null=True, verbose_name='Dados do Servidor')),
                ('esta_de_licenca', models.BooleanField(default=False, verbose_name='Está de Licença')),
                ('bloqueado_ate', models.DateField(blank=True, null=True, verbose_name='Bloqueado até (Suspensão)')),
                ('data_ultima_confirmacao', models.DateField(default=django.utils.timezone.now, verbose_name='Última Confirmação (90 dias)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'perfis',
            },
        ),
    ]
