# Generated by Django 4.2.30 on 2026-05-06 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServidorRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('nome_base', models.CharField(max_length=255, verbose_name='Nome na Base')),
                ('cargo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servidor RH (Base Espelho)',
                'verbose_name_plural': 'Servidores RH',
                'db_table': 'rh_servidores_base',
            },
        ),
        migrations.CreateModel(
            name='TicketDenunciaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_reclamada', models.CharField(max_length=50, verbose_name='Matrícula Reclamada')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido')], default='ABERTO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_resolvidas', to=settings.AUTH_USER_MODEL)),
                ('user_denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Denúncia',
                'verbose_name_plural': 'Tickets de Denúncia',
                'db_table': 'rh_tickets_denuncia',
            },
        ),
        migrations.AddConstraint(
            model_name='servidorrh',
            constraint=models.UniqueConstraint(fields=('cpf', 'matricula'), name='unique_cpf_matricula'),
        ),
    ]
