# Generated by Django 4.2.30 on 2026-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_solicitante',
            field=models.BooleanField(default=False, help_text='Concede permissão para solicitar reservas de espaços institucionais.', verbose_name='É Solicitante'),
        ),
    ]
