# Generated by Django 4.2.30 on 2026-05-06 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_servidorrh_ticketdenunciamatricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacaoChefia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('chefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinados', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chefias_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relação de Chefia',
                'verbose_name_plural': 'Relações de Chefia',
                'db_table': 'users_relacao_chefia',
            },
        ),
        migrations.AddConstraint(
            model_name='relacaochefia',
            constraint=models.UniqueConstraint(fields=('servidor', 'chefe'), name='unique_servidor_chefe'),
        ),
    ]
