# Generated by Django 4.2.30 on 2026-05-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='response_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Status HTTP de Saída'),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
