# Generated by Django 4.2.30 on 2026-05-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auditlog_response_status_profile_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Ex: SAD (máx. 15 caracteres)', max_length=15, unique=True, verbose_name='Sigla')),
                ('nome', models.CharField(help_text='Ex: Secretaria de Administração', max_length=255, verbose_name='Nome completo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'ordering': ['sigla'],
            },
        ),
    ]
